
### Tworzenie nowej kolejki górskiej
# Zapisuje ID nowej kolejki do zmiennej `coaster_id`
POST http://localhost:8080/api/coasters
Content-Type: application/json

{
  "nazwa": "Test Coaster",
  "liczba_personelu": 16,
  "liczba_klientow": 60000,
  "dl_trasy": 1800,
  "godziny_od": "8:00",
  "godziny_do": "16:00"
}

> {% client.global.set("coaster_id", response.body.coaster_id); %}

###

### Dodawanie wagonu do kolejki
# Używa zmiennej `coaster_id` i zapisuje ID nowego wagonu do zmiennej `wagon_id`
POST http://localhost:8080/api/coasters/{{coaster_id}}/wagons
Content-Type: application/json

{
  "ilosc_miejsc": 32,
  "predkosc_wagonu": 1.2
}

> {% client.global.set("wagon_id", response.body.wagon_id); %}

###

### Usuwanie wagonu z kolejki
# Używa zmiennych `coaster_id` i `wagon_id`
DELETE http://localhost:8080/api/coasters/{{coaster_id}}/wagons/{{wagon_id}}

###

### BŁĄD - Tworzenie kolejki z brakującymi danymi
POST http://localhost:8080/api/coasters
Content-Type: application/json

{
  "liczba_personelu": 10
}

###

### BŁĄD - Dodawanie wagonu do nieistniejącej kolejki
POST http://localhost:8080/api/coasters/nieistniejace-id/wagons
Content-Type: application/json

{
  "ilosc_miejsc": 16,
  "predkosc_wagonu": 1.5
}

###

### BŁĄD - Usuwanie nieistniejącego wagonu
DELETE http://localhost:8080/api/coasters/{{coaster_id}}/wagons/nieistniejace-id

###

### Pobieranie statusu kolejki
GET http://localhost:8080/api/coasters/{{coaster_id}}/status

> {% 
    client.test("Pobieranie statusu - sprawdzenie statusu personelu", function() {
        client.assert(response.status === 200, "Status odpowiedzi powinien byÄ‡ 200 OK");
        const body = response.body;
        client.assert(body.status === "success", "Status w odpowiedzi powinien byÄ‡ 'success'");
        client.assert(body.data.hasOwnProperty("personnel_status"), "OdpowiedÅº powinna zawieraÄ‡ 'personnel_status'");
        const personnelStatus = body.data.personnel_status;
        client.assert(personnelStatus.status === "warning", "Status personelu powinien byÄ‡ 'warning'");
        client.assert(personnelStatus.surplus === 15, "Nadmiar personelu powinien wynosiÄ‡ 15");
    });
%}


###

### BŁĄD - Pobieranie statusu nieistniejącej kolejki
GET http://localhost:8080/api/coasters/nieistniejace-id/status

###
### BŁĄD - Pobieranie statusu nieistniejącej kolejki
GET http://localhost:8080/api/coasters/nieistniejace-id/status
# Zapytanie, które testuje walidację (powinno zwrócić błąd 400)
Content-Type: application/json

{
  "liczba_personelu": "niepoprawnaliczba",
  "liczba_klientow": 1000,
  "dl_trasy": 500,
  "godziny_od": "09:00",
  "godziny_do": "18:00"
}
