

services:
  php:
    build:
      context: ./docker/php
      args:
        - APP_ENV=$APP_ENV
    image: coaster_php
    container_name: coaster_php
    volumes:
      - ./app:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APP_ENV=$APP_ENV # oddzielny env dla CI i aplikacji
    depends_on:
      - redis
    networks:
      - coaster_net

  nginx:
    image: nginx:latest
    container_name: coaster_nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - coaster_net

  redis:
    image: redis:7-alpine
    container_name: coaster_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - coaster_net

networks:
  coaster_net:
    driver: bridge

volumes:
  redis_data:
