services:
  php:
    build:
      context: ./docker/php
      args:
        - CI_ENVIRONMENT=${CI_ENVIRONMENT:-production}
    image: coaster_php
    container_name: coaster_php
    volumes:
      - ./app:/var/www/html
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CI_ENVIRONMENT=${CI_ENVIRONMENT:-production}
      - PHP_MEMORY_LIMIT=-1
      - DB_HOST=mysql
      - DB_DATABASE=coaster
      - DB_USERNAME=coaster_user
      - DB_PASSWORD=coaster_password
    depends_on:
      - redis
      - mysql  # dodaj zależność od mysql
    networks:
      - coaster_net

  nginx:
    image: nginx:latest
    container_name: coaster_nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - coaster_net

  redis:
    image: redis:7-alpine
    container_name: coaster_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - coaster_net

  mysql:
    image: mysql:8.0
    container_name: coaster_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: coaster
      MYSQL_USER: coaster_user
      MYSQL_PASSWORD: coaster_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - coaster_net

networks:
  coaster_net:
    driver: bridge

volumes:
  redis_data:
  mysql_data: